### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Elit3d** [steffendx/GoNorth#127]
Having an issue after installing, the screen is blank and I am not sure what to do now:
![2024-03-10 18_39_43-Window](https://github.com/steffendx/GoNorth/assets/9087576/01b25249-6ed4-4781-b297-9ecfd4cdd42e)

**Comment by steffendx** [comment]
Hi, it seems like you are missing roles. For this, you must navigate to the administration (found on the right next to your name). There you can open the user management and by pressing on the star icon in the user menu assign roles. For details, you can refer to the wiki here [Admin](https://github.com/steffendx/GoNorth/wiki/Administration#roles).

If you have already done this, it might be that you have to log out first and login back again, since the roles are stored in your login token.

Does that help?

**Comment by Elit3d** [comment]
Perfect thank you! That fixed my issue :)
