### ISSUE TITLE
[Feature Request] Concept map editor?

### ISSUE THREAD

**Issue by Wiadomy** [steffendx/GoNorth#21]
Hello! What do you think about adding a simple tile map editor to the Karta module?
I think it can be useful for people. Making maps in a different app is an option too, but after that we need to make map img, and modify map everytime we want to change something.

It's just a loose idea, I believe that it would be hard to implement.
Something like this: https://www.mipui.net/app
[Example Map.](https://cdn.discordapp.com/attachments/297032762634928128/356770005674622976/fa8b9fa.png)

**Comment by steffendx** [comment]
I think this would be very hard to implement and there are already a lot of very good apps for this. Therefore I will not implement this in GoNorth since I think exporting and importing the image works good as well and you will have a lot more features in the dedicated map tools than I will ever be able to implement in GoNorth. But thanks a lot for the input anyways! :)
