### ISSUE TITLE
[Enhancement] adding page for monster 

### ISSUE THREAD

**Issue by Aldiwildan77** [steffendx/GoNorth#53]
I would like to suggest that adding some pages for monster data will be helped in documenting. it's the same as NPC or items but focusing on monsters.

**Comment by steffendx** [comment]
Thank you for your suggestion! 

I usually use npcs for monsters but with a different template. Using a folder to organize your monsters you can then have a dedicated folder for monsters and maybe add a tag in the template like "Monster".

Does this work for you as well or can you elaborate on why monsters should have a special sections?

**Comment by Aldiwildan77** [comment]
"Does this work for you as well or can you elaborate on why monsters should have a special section?"

based on this question, I think the monster page will become a special section. Because I need some documentation about the mechanic stage by a monster and wiki can have a monster's section because it should be on the different section if someone read the wiki. 

It's my opinion about the monster section that I hope it will be a new feature.

**Comment by steffendx** [comment]
With mechanic state you mean the behaviour and so on? Because for this I am currently extending the npcs that you can also define a state machine for the npcs. So maybe the original approach I suggested might work.

I dont see the big benefit of having a specialized monster section if its the same as npcs to be honest. This would mainly add more items in the navigation without providing a new features. Using folders you should be able to organize the npcs for humans and monsters.

**Comment by steffendx** [comment]
Closed due to inactivity
