### ISSUE TITLE
Adding skills, npcs, and other things.

### ISSUE THREAD

**Issue by aknight2015** [steffendx/GoNorth#65]
I go into the skills management screen. I click on "Create Template" and from there I proceed to create a skills. It doesn't show up. I'm honestly not sure what I am supposed to do, and I hate to use the "Issues" thread to ask for help.

**Comment by steffendx** [comment]
Did you create a project first? You must have one default project in order for the system to work since everything needs to be associated with the project.  

Also after you create a template, this is the basic for creating real skills. So lets say you create a template "Attack Skill", this should then show up in the context menu when you press "New skill". Then you select the template "Attack skill" and can create a skill based on that template.  
The idea behind this is for you to create your different templates with their corresponding values (for items i.e. heal item, melee weapon, ... or for npcs for example human, monster, ...) and then create instances of that template (for example for the melee weapon "crude sword", "long sword", ...). 

Does the template show up in that context menu after you created it or is that also missing? Do you get any error while saving the template?

**Comment by aknight2015** [comment]
Yes, I did all of the above. I was finally able to get it working. I
want to thank you for helping me with this.

**Comment by steffendx** [comment]
Ok great! Thanks for letting me know and have fun with GoNorth.
